
import React from 'react';
import { AnalysisData } from '../types';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ScatterChart, Scatter, ZAxis,
  LineChart, Line
} from 'recharts';
import { Activity, Zap, Music2, AlertCircle, Sigma, Database, BrainCircuit, Waves, GitMerge, Library, Tag, Fingerprint, Microscope, GraduationCap, ScrollText, BookOpen, PenTool, ArrowRight, Wand2, Globe, Mic2, MonitorPlay, Users, Gauge, Scale, AlertTriangle, CheckCircle2, FileText, Download } from 'lucide-react';

interface Props {
  data: AnalysisData;
  onApplyFixes?: (instruction: string) => void;
  isApplying?: boolean;
}

export const AnalysisDashboard: React.FC<Props> = ({ data, onApplyFixes, isApplying = false }) => {
  const attributeData = [
    { subject: 'Complexity', A: data.musicalAttributes.complexity * 100, fullMark: 100 },
    { subject: 'Dissonance', A: data.musicalAttributes.dissonance * 100, fullMark: 100 },
    { subject: 'Rhythm', A: data.musicalAttributes.rhythmicVariety * 100, fullMark: 100 },
    { subject: 'Contour', A: data.musicalAttributes.melodicContour * 100, fullMark: 100 },
    { subject: 'Stability', A: data.musicalAttributes.tonalStability * 100, fullMark: 100 },
  ];

  const emotionData = data.deepAnalysis ? [
    { x: data.deepAnalysis.emotionalProfile.valence, y: data.deepAnalysis.emotionalProfile.arousal, z: 1 }
  ] : [];

  const melodicIntervalData = data.advancedTraitModeling?.jSymbolic.melodicIntervalHistogram.map((val, idx) => ({
      interval: `${idx}st`,
      count: val
  })) || [];

  const handleDownloadReport = () => {
    const report = generateMarkdownReport(data);
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Analysis_Report_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateMarkdownReport = (d: AnalysisData) => {
    let md = `# Musicological Analysis Report\n`;
    md += `Generated by Opus Infinite AI Composer\n`;
    md += `Date: ${new Date().toLocaleString()}\n\n`;

    md += `## 1. Executive Summary\n`;
    md += `> ${d.comprehensiveLexiconAnalysis?.expertCommentary || 'No summary available.'}\n\n`;

    md += `## 2. Technical Validation\n`;
    if (d.instrumentRanges) {
        md += `### Instrument Ranges\n`;
        d.instrumentRanges.forEach(inst => {
            md += `- **${inst.instrument}**: Rating: ${inst.overallRating} (${inst.percentInRange}% Playable). Issues: ${inst.issues.join(', ') || 'None'}\n`;
        });
        md += `\n`;
    }
    if (d.zedClefData) {
        md += `### Tessitural Balance (Zed Clef)\n`;
        md += `- **Status**: ${d.zedClefData.isCompliant ? 'BALANCED' : 'UNBALANCED'}\n`;
        md += `- **Score**: ${d.zedClefData.balanceScore}/100\n`;
        md += `- **Spread**: ${d.zedClefData.intervalSpread}\n`;
        md += `- **Plan**: ${d.zedClefData.rectificationPlan}\n\n`;
    }

    md += `## 3. Musical Vectors\n`;
    md += `- Complexity: ${d.musicalAttributes.complexity}\n`;
    md += `- Dissonance: ${d.musicalAttributes.dissonance}\n`;
    md += `- Tonal Stability: ${d.musicalAttributes.tonalStability}\n\n`;

    if (d.comprehensiveLexiconAnalysis) {
        const lex = d.comprehensiveLexiconAnalysis;
        md += `## 4. Cultural & Historical Context\n`;
        md += `### History\n${lex.culturalContext.historicalBackground}\n\n`;
        md += `### Social Function\n${lex.culturalContext.socialFunction}\n\n`;
        md += `### Performance Practice\n${lex.culturalContext.performancePractice}\n\n`;
    }

    if (d.deepAnalysis) {
        md += `## 5. Theoretical Frameworks\n`;
        md += `### Schenkerian Analysis\n${d.deepAnalysis.theoreticalFrameworks.schenkerian}\n\n`;
        md += `### GTTM (Lerdahl/Jackendoff)\n${d.deepAnalysis.theoreticalFrameworks.gttm}\n\n`;
        md += `### Neo-Riemannian Theory\n${d.deepAnalysis.theoreticalFrameworks.neoRiemannian}\n\n`;
    }

    md += `## 6. Actionable Feedback\n`;
    md += `${d.comprehensiveLexiconAnalysis?.actionableFeedback || 'Continue refining the piece.'}\n`;

    return md;
  };

  return (
    <div className="space-y-6 animate-fade-in p-4 bg-gray-900 rounded-xl border border-gray-800">
      
      {/* 1. TOP LEVEL: TECHNICAL & ORCHESTRATION VALIDATION */}
      {(data.instrumentRanges || data.zedClefData) && (
        <div className="bg-gray-800/30 border border-gray-700 rounded-lg overflow-hidden animate-in fade-in slide-in-from-top-4">
            <div className="bg-gray-800/80 p-3 border-b border-gray-700 flex items-center justify-between">
                <div className="flex items-center gap-2">
                    <Gauge className="w-5 h-5 text-indigo-400" />
                    <h3 className="text-sm font-bold text-gray-200 uppercase tracking-wider">Technical Orchestration Validation</h3>
                </div>
                <div className="flex items-center gap-2">
                    <button 
                        onClick={handleDownloadReport}
                        className="flex items-center gap-2 px-3 py-1 bg-gray-700 hover:bg-gray-600 text-gray-200 rounded text-xs font-bold transition-all border border-gray-600 shadow-lg"
                    >
                        <FileText className="w-3 h-3" />
                        Download Report (.md)
                    </button>
                    {onApplyFixes && (
                        <button 
                            onClick={() => onApplyFixes(data.comprehensiveLexiconAnalysis?.actionableFeedback || "")}
                            disabled={isApplying}
                            className="flex items-center gap-2 px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white rounded text-xs font-bold transition-all shadow-lg shadow-emerald-900/20 disabled:opacity-50 border border-emerald-500/50"
                        >
                            {isApplying ? (
                                <>
                                    <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                    Rectifying...
                                </>
                            ) : (
                                <>
                                    <Wand2 className="w-3 h-3" />
                                    Auto-Rectify Issues
                                </>
                            )}
                        </button>
                    )}
                </div>
            </div>

            <div className="p-4 grid grid-cols-1 lg:grid-cols-2 gap-6">
                
                {/* A. Instrument Range Analysis */}
                {data.instrumentRanges && (
                    <div className="space-y-4">
                        <h4 className="text-xs font-bold text-gray-500 uppercase flex items-center gap-2">
                            <Music2 className="w-4 h-4" />
                            Professional Range Check
                        </h4>
                        <div className="space-y-3">
                            {data.instrumentRanges.map((inst, i) => (
                                <div key={i} className="bg-gray-900/50 p-3 rounded border border-gray-800">
                                    <div className="flex justify-between items-center mb-1">
                                        <span className="text-sm font-bold text-gray-300">{inst.instrument}</span>
                                        <span className={`text-xs font-mono px-2 py-0.5 rounded ${
                                            inst.overallRating === 'PERFECT' ? 'bg-emerald-900/30 text-emerald-400' :
                                            inst.overallRating === 'GOOD' ? 'bg-blue-900/30 text-blue-400' :
                                            inst.overallRating === 'STRAINED' ? 'bg-yellow-900/30 text-yellow-400' :
                                            'bg-red-900/30 text-red-400'
                                        }`}>
                                            {inst.overallRating}
                                        </span>
                                    </div>
                                    
                                    <div className="space-y-1 mb-2">
                                        <div className="flex justify-between text-[10px] text-gray-500">
                                            <span>Playable</span>
                                            <span>{inst.percentInRange}%</span>
                                        </div>
                                        <div className="w-full bg-gray-700 h-1.5 rounded-full overflow-hidden">
                                            <div className={`h-full rounded-full ${inst.percentInRange === 100 ? 'bg-emerald-500' : 'bg-red-500'}`} style={{ width: `${inst.percentInRange}%` }} />
                                        </div>

                                        <div className="flex justify-between text-[10px] text-gray-500 pt-1">
                                            <span>Prof. Comfort</span>
                                            <span>{inst.percentProfessional}%</span>
                                        </div>
                                        <div className="w-full bg-gray-700 h-1.5 rounded-full overflow-hidden">
                                            <div className={`h-full rounded-full ${inst.percentProfessional > 90 ? 'bg-blue-500' : 'bg-yellow-500'}`} style={{ width: `${inst.percentProfessional}%` }} />
                                        </div>
                                    </div>

                                    {inst.issues.length > 0 && (
                                        <div className="mt-2 pt-2 border-t border-gray-800">
                                            <span className="text-[10px] text-red-400 font-bold block mb-1">WARNINGS:</span>
                                            <ul className="list-disc pl-3 space-y-0.5">
                                                {inst.issues.map((issue, idx) => (
                                                    <li key={idx} className="text-[10px] text-gray-400">{issue}</li>
                                                ))}
                                            </ul>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* B. Zed Clef Analysis */}
                {data.zedClefData && (
                    <div className="space-y-4">
                        <h4 className="text-xs font-bold text-gray-500 uppercase flex items-center gap-2">
                            <Scale className="w-4 h-4" />
                            Zed Clef (Tessitural Balance)
                        </h4>
                        
                        <div className={`p-4 rounded-lg border ${data.zedClefData.isCompliant ? 'bg-emerald-900/10 border-emerald-500/30' : 'bg-red-900/10 border-red-500/30'}`}>
                            <div className="flex items-center gap-3 mb-4">
                                {data.zedClefData.isCompliant ? (
                                    <CheckCircle2 className="w-8 h-8 text-emerald-500" />
                                ) : (
                                    <AlertTriangle className="w-8 h-8 text-red-500" />
                                )}
                                <div>
                                    <h5 className={`text-lg font-bold ${data.zedClefData.isCompliant ? 'text-emerald-400' : 'text-red-400'}`}>
                                        {data.zedClefData.isCompliant ? 'Balanced (Pass)' : 'Unbalanced (Fail)'}
                                    </h5>
                                    <p className="text-xs text-gray-400">Balance Score: {data.zedClefData.balanceScore}/100 • Spread: {data.zedClefData.intervalSpread}</p>
                                </div>
                            </div>

                            {!data.zedClefData.isCompliant && (
                                <div className="space-y-3">
                                    <div className="bg-gray-900/50 p-3 rounded text-xs text-gray-300 border border-gray-800">
                                        <span className="text-gray-500 font-bold block mb-1">RECTIFICATION PLAN:</span>
                                        {data.zedClefData.rectificationPlan}
                                    </div>
                                    <div className="space-y-1">
                                        {data.zedClefData.issues.map((issue, idx) => (
                                            <div key={idx} className="flex items-start gap-2 text-[10px] text-red-300/80">
                                                <AlertCircle className="w-3 h-3 shrink-0 mt-0.5" />
                                                <span>{issue}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                            
                            {data.zedClefData.isCompliant && (
                                <p className="text-xs text-emerald-300/80 italic">
                                    "The vertical voicing adheres to the Rule of the Sixth, ensuring clear projection across all voices."
                                </p>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
      )}

      {/* 2. STRUCTURAL CHARTS */}
      <div className="flex items-center justify-between mb-4 mt-8 border-t border-gray-800 pt-6">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Activity className="w-5 h-5 text-indigo-400" />
          Structural Analysis
        </h2>
        <span className="text-xs font-mono text-gray-400 bg-gray-800 px-2 py-1 rounded">
          Simulating Music21/Librosa
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-gray-800/50 p-4 rounded-lg border border-gray-700 h-[300px]">
          <h3 className="text-sm font-semibold text-gray-300 mb-2 flex items-center gap-2">
            <Zap className="w-4 h-4 text-yellow-400" />
            Musical Vectors
          </h3>
          <ResponsiveContainer width="100%" height="100%">
            <RadarChart cx="50%" cy="50%" outerRadius="80%" data={attributeData}>
              <PolarGrid stroke="#4b5563" />
              <PolarAngleAxis dataKey="subject" tick={{ fill: '#9ca3af', fontSize: 10 }} />
              <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
              <Radar
                name="Score"
                dataKey="A"
                stroke="#818cf8"
                strokeWidth={2}
                fill="#6366f1"
                fillOpacity={0.4}
              />
              <Tooltip 
                contentStyle={{ backgroundColor: '#1f2937', border: '1px solid #374151', color: '#fff' }}
              />
            </RadarChart>
          </ResponsiveContainer>
        </div>

        <div className="bg-gray-800/50 p-4 rounded-lg border border-gray-700 h-[300px]">
          <h3 className="text-sm font-semibold text-gray-300 mb-2 flex items-center gap-2">
            <Music2 className="w-4 h-4 text-emerald-400" />
            Pitch Distribution
          </h3>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data.noteDistribution}>
              <CartesianGrid strokeDasharray="3 3" stroke="#374151" vertical={false} />
              <XAxis dataKey="note" stroke="#9ca3af" fontSize={10} />
              <YAxis stroke="#9ca3af" fontSize={10} />
              <Tooltip 
                cursor={{ fill: '#374151', opacity: 0.4 }}
                contentStyle={{ backgroundColor: '#1f2937', border: '1px solid #374151', color: '#fff' }}
              />
              <Bar dataKey="count" fill="#34d399" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {data.datasetBenchmarks && (
        <div className="space-y-4">
            <div className="bg-gray-800/30 p-4 rounded-lg border border-gray-700">
                <h3 className="text-sm font-semibold text-gray-300 mb-4 flex items-center gap-2">
                    <Database className="w-4 h-4 text-cyan-400" />
                    Core Dataset Benchmarking
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                        <div className="flex justify-between items-end mb-2">
                            <span className="text-xs text-gray-400">Tegridy Similarity</span>
                            <span className="text-xl font-mono text-cyan-400">{data.datasetBenchmarks.tegridySimilarity}%</span>
                        </div>
                        <div className="w-full bg-gray-700 h-1.5 rounded-full overflow-hidden">
                            <div className="bg-cyan-500 h-full rounded-full" style={{ width: `${data.datasetBenchmarks.tegridySimilarity}%` }} />
                        </div>
                        <p className="text-[10px] text-gray-500 mt-2">Match: {data.datasetBenchmarks.closestTegridyMatch}</p>
                    </div>

                    <div className="bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                        <div className="flex justify-between items-end mb-2">
                            <span className="text-xs text-gray-400">Million Song Sim.</span>
                            <span className="text-xl font-mono text-indigo-400">{data.datasetBenchmarks.millionSongSimilarity}%</span>
                        </div>
                        <div className="w-full bg-gray-700 h-1.5 rounded-full overflow-hidden">
                            <div className="bg-indigo-500 h-full rounded-full" style={{ width: `${data.datasetBenchmarks.millionSongSimilarity}%` }} />
                        </div>
                    </div>

                    <div className="bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                        <div className="flex justify-between items-end mb-2">
                            <span className="text-xs text-gray-400">Structural Rarity</span>
                            <span className="text-xl font-mono text-pink-400">{data.datasetBenchmarks.structuralRarity}%</span>
                        </div>
                        <div className="w-full bg-gray-700 h-1.5 rounded-full overflow-hidden">
                            <div className="bg-pink-500 h-full rounded-full" style={{ width: `${data.datasetBenchmarks.structuralRarity}%` }} />
                        </div>
                    </div>
                </div>
            </div>

            <div className="bg-gray-800/30 p-4 rounded-lg border border-gray-700">
                <h3 className="text-sm font-semibold text-gray-300 mb-4 flex items-center gap-2">
                    <Library className="w-4 h-4 text-orange-400" />
                    Extended Corpus Analysis (Audio & Symbolic)
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    <div className="bg-gray-900/50 p-3 rounded border border-gray-800 flex items-center justify-between">
                         <div>
                            <span className="text-xs text-gray-500 block">GTZAN Genre</span>
                            <span className="text-sm font-mono text-gray-200">{data.datasetBenchmarks.gtzanGenreMatch || 'N/A'}</span>
                         </div>
                         <div className="h-2 w-2 rounded-full bg-orange-500 animate-pulse"></div>
                    </div>
                    
                    <div className="bg-gray-900/50 p-3 rounded border border-gray-800">
                        <div className="flex justify-between mb-1">
                             <span className="text-xs text-gray-500">MAESTRO Expressivity</span>
                             <span className="text-xs text-gray-300">{data.datasetBenchmarks.maestroExpressivity || 0}%</span>
                        </div>
                        <div className="w-full bg-gray-700 h-1 rounded-full overflow-hidden">
                            <div className="bg-orange-500 h-full rounded-full" style={{ width: `${data.datasetBenchmarks.maestroExpressivity || 0}%` }} />
                        </div>
                    </div>

                     <div className="bg-gray-900/50 p-3 rounded border border-gray-800">
                        <div className="flex justify-between mb-1">
                             <span className="text-xs text-gray-500">MusicNet Complexity</span>
                             <span className="text-xs text-gray-300">{data.datasetBenchmarks.musicNetComplexity || 0}%</span>
                        </div>
                        <div className="w-full bg-gray-700 h-1 rounded-full overflow-hidden">
                            <div className="bg-blue-500 h-full rounded-full" style={{ width: `${data.datasetBenchmarks.musicNetComplexity || 0}%` }} />
                        </div>
                    </div>
                </div>
            </div>
        </div>
      )}
      
      {data.advancedTraitModeling && (
        <div className="bg-gray-800/30 p-4 rounded-lg border border-gray-700">
             <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                    <Microscope className="w-5 h-5 text-lime-400" />
                    <h3 className="text-sm font-semibold text-gray-300">Advanced Feature Extraction</h3>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                 <div className="col-span-1 lg:col-span-1 bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                    <h4 className="text-xs font-semibold text-gray-400 uppercase mb-3 flex items-center gap-2">
                        <Fingerprint className="w-4 h-4 text-lime-400" />
                        Stylistic Fingerprint (MelSpy)
                    </h4>
                    
                    <div className="space-y-4">
                         <div>
                            <div className="flex justify-between text-xs mb-1">
                                <span className="text-gray-500">Harmonic Entropy</span>
                                <span className="text-gray-300">{data.advancedTraitModeling.stylisticFingerprint.harmonicEntropy}</span>
                            </div>
                            <div className="w-full bg-gray-700 h-1 rounded-full">
                                <div className="bg-lime-500 h-full rounded-full" style={{ width: `${Math.min(data.advancedTraitModeling.stylisticFingerprint.harmonicEntropy * 20, 100)}%` }} />
                            </div>
                         </div>
                    </div>
                    
                    <div className="mt-4 p-3 bg-gray-800/50 rounded border border-gray-700">
                         <span className="text-[10px] text-gray-500 uppercase block mb-1">Implied Texture</span>
                         <span className="text-sm font-mono text-lime-300">{data.advancedTraitModeling.stylisticFingerprint.orchestralTexture}</span>
                    </div>
                 </div>

                 <div className="col-span-1 lg:col-span-2 bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                    <h4 className="text-xs font-semibold text-gray-400 uppercase mb-3 flex items-center gap-2">
                        <Sigma className="w-4 h-4 text-cyan-400" />
                        jSymbolic Feature Vectors
                    </h4>
                    
                    <div className="grid grid-cols-2 gap-4 mb-4">
                        <div className="bg-gray-800 p-3 rounded">
                            <span className="block text-xs text-gray-500">Avg. Chord Density</span>
                            <span className="text-xl font-mono text-cyan-400">
                                {data.advancedTraitModeling.jSymbolic.chordDensity}
                            </span>
                        </div>
                    </div>
                 </div>
            </div>
        </div>
      )}

      {data.comprehensiveLexiconAnalysis && (
        <div className="bg-gradient-to-br from-indigo-900/20 to-purple-900/20 border border-indigo-500/30 rounded-lg p-6">
            <div className="flex items-center gap-3 mb-6 border-b border-indigo-500/20 pb-4">
                <div className="bg-indigo-500/20 p-2 rounded-lg">
                    <GraduationCap className="w-6 h-6 text-indigo-300" />
                </div>
                <div>
                    <h3 className="text-lg font-bold text-indigo-100">Expert Team Analysis (Opus Infinite Lexicon)</h3>
                </div>
            </div>

            <div className="space-y-6">
                <div className="bg-black/20 p-4 rounded-lg border-l-4 border-indigo-500">
                    <h4 className="text-sm font-semibold text-gray-300 mb-2 flex items-center gap-2">
                        <ScrollText className="w-4 h-4 text-indigo-400" />
                        Executive Synthesis
                    </h4>
                    <p className="text-sm text-gray-300 leading-relaxed italic">
                        "{data.comprehensiveLexiconAnalysis.expertCommentary}"
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div className="space-y-2">
                        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Core Musical Elements</h4>
                        <div className="bg-gray-800/40 p-3 rounded border border-gray-700/50 space-y-2">
                            <div>
                                <span className="text-[10px] text-cyan-400 block uppercase">Rhythm & Metre</span>
                                <p className="text-xs text-gray-400">{data.comprehensiveLexiconAnalysis.coreElements.rhythmAndMetre}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};
